title: Zoujian's Homepage
page-top-title: Zoujian Xie
top-section-bg-text: Be what you wanna be
home-subtitle: Zoujian Xie
copyright-text: '&copy; Zoujian 2023-2025. All Rights Reserved.'
site_name: "Zoujian Xie"
site_description: "Computer Technology"
email: "leibniz472330850@gmail.com"
